rocketdb:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://chat.lho.io
    - Accounts_UseDNSDomainCheck=True
  links:
    - rocketdb:db
  ports:
    - 3000:3000