version: '3.7'
services:
  app:
    image: drone/drone:1.0.0-rc.5
    container_name: drone_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ DATA_DIR }}:/data"
    environment:
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_GITLAB_SERVER=https://gitlab.com
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_TLS_AUTOCERT=false
      - DRONE_SERVER_PROTO=https
      - DRONE_SERVER_HOST=drone.lho.io
      - DRONE_GITLAB_CLIENT_ID=${DRONE_GITLAB_CLIENT_ID}
      - DRONE_GITLAB_CLIENT_SECRET=${DRONE_GITLAB_CLIENT_SECRET}
    restart: always
    ports:
      - 127.0.0.1:{{ PORT_NUM }}:80
