version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: wordpress_proxy
    ports:
      - '8081:80'
    volumes:
      - /mnt/data/wordpress/nginx/conf.d:/etc/nginx/conf.d
      - /mnt/data/wordpress/nginx/logs:/var/log/nginx
      - /mnt/data/wordpress/data:/var/www/html
    links:
      - app
    restart: always

  db:
    image: mariadb
    container_name: wordpress_db
    volumes:
      - /mnt/data/wordpress/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always

  app:
    image: wordpress:php7.2-fpm
    container_name: wordpress_app
    volumes:
      - /mnt/data/wordpress/data:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    links:
      - db
    restart: always