version: '2'

services:
  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    volumes:
      - /mnt/data/nextcloud/db:/var/lib/mysql

  app:
    image: nextcloud
    container_name: nextcloud_app
    ports:
      - 127.0.0.1:8080:80
    depends_on:
      - db
    links:
      - db
    volumes:
      - /mnt/data/nextcloud/app:/var/www/html
    restart: always

  web:
    image: phpmyadmin/phpmyadmin
    container_name: nextcloud_admin
    ports:
      - 127.0.0.1:8083:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    links:
      - db